---
title: "viz_part_01"
output: github_document
---

```{r setup, include=FALSE}

```

##Let's import data

```{r}
library(tidyverse)
library(patchwork)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df%>%
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(aes(color=name),alpha=0.5)
```

##Scatterplot

But better this time

```{r}
weather_df%>%
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(aes(color=name),alpha=0.5)+
  labs(
    x="minimum daily temp (C)",
    y="maximum daily temp (C)",
    title="scatterplot of daily temp extremes",
    caption="data come from the rnoaa package")+
  scale_x_continuous(
    breaks=c(-10,0,15),
    labels=c("-10C","0","15")
  )+
  scale_y_continuous(
    trans="sqrt"
  )
```


```{r}
weather_df%>%
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(aes(color=name),alpha=0.5)+
  labs(
    x="minimum daily temp (C)",
    y="maximum daily temp (C)",
    title="scatterplot of daily temp extremes",
    caption="data come from the rnoaa package")+
  scale_color_hue(    
    name="Location",
    h=c(100,300))
```

```{r}
ggp_weather=weather_df%>%
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(aes(color=name),alpha=0.5)+
  labs(
    x="minimum daily temp (C)",
    y="maximum daily temp (C)",
    title="scatterplot of daily temp extremes",
    caption="data come from the rnoaa package")+
  viridis::scale_color_viridis(    
    name="Location",discrete=TRUE)
```

#Themes
```{r}
ggp_weather+
theme(legend.position="bottom")
```

```{r}
ggp_weather+
  theme_bw()
```

```{r}
ggp_weather+
  theme_minimal()
```

```{r}
ggp_weather+
  theme_classic()
```

```{r}
ggp_weather+
  theme_minimal()+
theme(legend.position="bottom") #Order for themes does matter
``` 

Jeff prefers color viridis and theme_minimal

```{r} 
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

##Data in geom()
```{r}
central_park_df=
  weather_df%>%
  filter(name=="CentralPark_NY")

waikiki_df=
  weather_df%>%
  filter(name=="Waikiki_HA")

ggplot(waikiki_df,aes(x=date, y=tmax))+
  geom_point()+
  geom_line(data=central_park_df)
```

##Patchwork...

```{r}
tmax_tmin_plot=
  weather_df%>%
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point()

prcp_density_plot=
  weather_df%>%
  filter(prcp>0)%>%
  ggplot(aes(x=prcp,fill=name))+
  geom_density(alpha=.5)
  theme(legend.position="none")
  
  seasonality_plot=
    weather_df%>%
    ggplot(aes(x=date,y=tmax,color=name))+
    geom_point(alpha=0.5)+
    geom_smooth(se=FALSE)
    theme(legend.position="name")
    
(tmax_tmin_plot+prcp_density_plot)/seasonality_plot

```

##Data manipulation

#reorder values
```{r}
weather_df%>%
  mutate(name=fct_relevel(name,"Waikiki_HA"))%>%
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()
```

#reorder values in the order of tmax
```{r}
weather_df%>%
  mutate(name=fct_reorder(name,tmax))%>%
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()
```

```{r}
pulse_df=
  haven::read_sas("data/public_pulse_data.sas7bdat")%>%
  janitor::clean_names()%>%
pivot_longer(
  bdi_score_bl:bdi_score_12m,
  names_to="visit",
  values_to="bdi",
  names_prefix="bdi_score_"
)%>%
  select(id, visit, everything())%>%
  mutate(
    visit=fct_relevel(visit,"bl")
  )

pulse_df%>%
  ggplot(aes(x=visit,y=bdi))+
  geom_boxplot()

```



