---
title: "viz_part_01"
output: github_document
---

```{r setup, include=FALSE}

```

##Let's import data

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Let's make a scatterplot.

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax))+
  geom_point()
```

Let's make the same scatterplot, but different

```{r}
weather_df%>%
  drop_na()%>%
  filter(name == "CentralPark_NY") %>%
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point()
```

Let's keep making the same plot, but different.

```{r}
weather_scatterplot=
  weather_df%>%
  drop_na()%>%
  ggplot(aes(x=tmin, y=tmax))

weather_scatterplot+
  geom_point()
```

Let's fancy this up a bit

```{r}
weather_df%>%
  ggplot(aes(x=tmin,y=tmax, color=name))+
  geom_point()
```

```{r}
weather_df%>%
  ggplot(aes(x=tmin,y=tmax))+
  geom_point(aes(color=name))+
  geom_smooth()
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth()
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
weather_df%>%
  filter(name == "CentralPark_NY") %>%
  mutate(
    tmin_f=tmin*(9/5) + 32,
    tmax_f=tmax*(9/5) + 32)%>%
  ggplot(aes(x=tmin_f, y=tmax_f)) +
  geom_point(alpha=.5)+
  geom_smooth(method="lm", se=FALSE)
```

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5)+
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```
```{r}
ggplot(weather_df, aes(x = tmax)) + 
  geom_histogram()
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")
```

```{r}
#Histogram
ggplot(weather_df, aes(x = prcp)) + 
  geom_histogram()

#Density plot
ggplot(weather_df, aes(x = prcp, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")

#Boxplot
ggplot(weather_df, aes(x = name, y = prcp)) + geom_boxplot()

#Violin plot
ggplot(weather_df, aes(x = name, y = prcp)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")

#Ridge plot
ggplot(weather_df, aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)
```

